# Request info message
requestInfoReplyComment: >
  Thanks for opening this PR! 
  We would appreciate it if you could provide us with more info about your PR :pray:

# tag name
requestInfoLabelToAdd: needs-more-info

# First PR message
newPRWelcomeComment: >
  Thanks so much for opening your first PR here! :raised_hands:

# First merrged PR message
firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!

# New issue message
newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!

requestInfoOn:
  pullRequest: true